<?php

declare(strict_types=1);

namespace Bolzer\TsConstEnum\Commands;

use Bolzer\TsConstEnum\Configuration\Config;
use Bolzer\TsConstEnum\Services\Generator;
use Composer\Autoload\ClassLoader;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class GenerateCommand extends Command
{
    public function __construct(
        private Config $config,
        private ClassLoader $classLoader
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this
            ->setName('generate')
            ->setDescription('Transforms annotated PHP constants to Typescript')
            ->setHelp('Transforms PHP constants to typescript and generates a file containing the typescript constants')
        ;
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $result = (new Generator($this->config, $this->classLoader))->generate();

        $this->writeContentToConstantFile($result);

        $output->writeln(\sprintf('<info>Generated %s constants</info>', \count($result)));

        return 1;
    }

    private function writeContentToConstantFile(array $fileContent): void
    {
        $filePath = $this->config->getOutputPath();

        $dir = dirname($filePath);

        if (!is_dir($dir) && !mkdir($dir, 0777, true) && !is_dir($dir)) {
            throw new \RuntimeException(sprintf('Directory "%s" was not created', $dir));
        }

        if (\file_exists($filePath)) {
            \unlink($filePath);
        }

        if ($this->config->isShouldAddGenerateHint()) {
            \array_unshift($fileContent, ...$this->getHeaderOfGeneratedFile());
        }

        file_put_contents($filePath, implode(\PHP_EOL, $fileContent));
    }

    private function getHeaderOfGeneratedFile(): array
    {
        return [
            '/*',
            'This Code was auto generated by the PHPConstAndPatchWorkEnumsToTypeScript Command',
            'Do not touch this code under any circumstances. Just run make',
            'php bin/php_const_to_typescript if you want to refresh this file',
            '*/',
        ];
    }
}
